### PR TITLE
More test cases for handover and SignatureRecord

### PR DESCRIPTION
**Pull request by skjolber**

### CODE REVIEW

**Comment by grundid** [comment]
Yeah! Signature record. :)

Do plan to add functionality how to actually sign and verify the NDEF records? This would be really cool.

**Comment by skjolber** [comment]
I have no plans to make a 'validation engine' yet, but it seems like a really useful feature. I am not sure where to put higher-level logic which runs across multiple records, but maybe some wizards would be useful in the NDEF Eclipse editor.

**Comment by skjolber** [comment]
Seems like someone already did some work on signatures, but it all seems a bit immature: http://code.google.com/p/nfcsigning/

**Comment by grundid** [comment]
Ok. I'm just asking because we might need to do some refactoring to get it to work. 

I see the signing and verifying functions as part of the encoder/decoder process so let's discuss it together once you have some time. We definitely need some real life examples for the tests ;)

**Pull request merged**
