### PR TITLE
More error messages and hardening of low-level NdefRecord parsing

### PR DESCRIPTION
**Pull request by skjolber**
Added some more detailed error messages in one of the Handover Records. Rewrote some of the low-level ndef record decoding - basically the current approach should be hardened by checking for EOF and avoid using InputStream.available() altogether. Also there is no real distinction between 
1. read ndef messages untill end of buffer
2. read ndef messages, start flag first and till end flag 

Now, the spec seems a little shaky on this, the GenericControlRecord spec examples seems to require end and start flags individually on all subrecords, whereas in other cases, the approach is read start flag record first, red n records, and then stop at reading end flag record. 

While I am pretty sure everything is supposed to be streaming-friendly (why make something like chunked records if this is not the idea), I guess the spec is unclear and in those cases we'd like to do 1 (other might conclude that 2 is 1), in all the other cases we'd like to do 2. 

So I have made the above distinction with the added improvement of solid InputStream support, correspondinly

1: decodeFully(...)
2: decode(...)

The improved coded spotted an error in a test case, where reading a payload array silently was cut short because EOF.

Last three edits: Added some terminal status and decode logic which were necessary to make the eclipse plugin integration with card terminals.

### CODE REVIEW

**Comment by grundid** [comment]
Thanks Thomas for this pull request.

I had some time to go over it and I like all your checks for end of stream.
I think we should change the InputStream for the java.io.DataInput interface because this already does all the EOF checks and also is able to read all the primitive data types from the stream. 
Sorry I didn't come earlier with this.

However I'm not happy with the decodeFully methods. I would suggest to make NdefMessageDecoder an interface and then support different implementations. 

What do you think?

**Comment by skjolber** [comment]
I have refactored the encoding/decoding and created more simple NdefEncoder/NdefDecoder in place of the NdefMessageEncoder/NdefMessageDecoder. NdefMessageEncoder/NdefMessageDecoder are now more low-level and deals with NdefRecords only. 

Cases 1 and 2 above are separated by a boolean - the default case is that message start and message end flags are not enforced (i.e. decodeFully) since we as in a general rule want to be flexible/lenient in decoding.

See what you make of it - we could use a DataInputStream but the current approach saves the creation of the DataInputStream instance and so is a mini optimization.

I was not entirely sure what some of those test cases I modified were supposed to do, since there was no doc, have a look at them(?). Especially in NdefMessageDecoderTest there was a mime record test which which was faulty.

**Comment by skjolber** [comment]
Also I feel that collections of records are not sensible, any reason why a list is not used throughout the project?

**Comment by grundid** [comment]
Please, let us discuss things before we create facts ;)

I would really like to see the DataInput interface in use in the NdefDecoder since it would really simplify the code and enhance readability. Also DataOutput could be used in the encoder.

Also it would be better to keep the names of the classes as they were. At least for the time being. nfctools is a library and other developers might depend on it. 

However I would welcome the NdefEncoder and NdefDecoder as interfaces.

**Comment by skjolber** [comment]
Okey lets discuss some more. 
- changes to other developers are minimal as only the class name changes - functionality-wise it is still all there. 
- the new setup has better scoped classes and is more readable than the old, for example NdefMessageDecoder now actually decodes to NdefMessages
- the new NdefEncoder and NdefDecoder hides more low-level functionality from devs than the old equivalent

I think that NFC use is still in its infancy and we should not be reluctant to make changes - it is not like we are forcing anyone to update, and later it will be even harder.

**Comment by grundid** [comment]
I'm currently trying to merge your code but I'm wondering why do we need two different decode methods in NdefMessageDecoder. 
Isn't it possible to just convert the byte array into an inputstream and use just one method?

**Comment by skjolber** [comment]
Strictly speaking, we only need one - but both have their practical applications. The byte one serves as an optimalization as an often used case is parsing from subrecords in for example smartposterrecord or some of the handover records.

**Pull request closed without merging**
